version: '3.8'

services:
  perplexica:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
    ports:
      - 3000:3000
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml

  searxng:
    image: searxng/searxng
    restart: unless-stopped
    ports:
      - 4000:8080
    volumes:
      - ./searxng:/etc/searxng:rw

volumes:
  backend-dbstore:
  uploads:
